INFO/INFO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
]

# urls.py

from django.conf import settings
from django.conf.urls.static import static

# urlpatterns = [
#     # ... Tus otras URL aquí ...
# ]

# # Configuración para servir archivos de medios en desarrollo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

INFO/blog/urls.py
from django.urls import path

from . import views



app_name = "blog"
urlpatterns = [
    path("", views.index_view, name="index"),
    # path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    # path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # path("<int:question_id>/vote/", views.vote, name="vote"),
    path("blog/", views.blog, name="blog"),
    path("post/<int:post_id>/", views.post, name="post"),
    # path("blog/register", views.register_view, name="register")
    path("blog/register", views.register_view, name="register"),
    path("blog/login", views.login_view, name="login"),
    path("blog/logout", views.logout_view, name="logout"),
    path("blog/new_post", views.new_post_view, name="new_post"),
    path("delete_comment/<int:comentario_id>/", views.delete_comment, name="delete_comment"),
    path('edit_users/', views.edit_users_permissions, name='edit_users_permissions'),
    path("post/<int:post_id>/editar/", views.editar_post, name="editar_post"),
    path("post/<int:post_id>/eliminar/", views.eliminar_post, name="eliminar_post"),
    path("blog/modify_user", views.modify_user, name="modify_user"),
    path("blog/buscar", views.buscar_articulo, name="buscar_articulos"),
    path("categorias/", views.crear_editar_categorias, name="crear_editar_categorias"),
    path('categoria/<int:categoria_id>/json/', views.categoria_json, name='categoria_json'),
    path('etiqueta/nueva-o-editar/', views.crear_editar_etiqueta, name='crear_editar_etiqueta'),

]

INFO/blog/forms.py
from django import forms
from .models import Articulo, Categoria, Etiqueta, Usuarios, Comentario, Categoria_Articulo, MensajeContacto
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError 
from PIL import Image

class ArticuloForm(forms.ModelForm):
    
    def clean_imagen(self):
        imagen = self.cleaned_data['imagen']

        if imagen:
            img = Image.open(imagen)
            if img.width > 1020 or img.height > 768:
                raise ValidationError("La imagen no puede ser mayor de 1020x768 píxeles.")

        return imagen
    
    # def __init__(self, *args, **kwargs):
    #     super(ArticuloForm, self).__init__(*args, **kwargs)
    #     instance = kwargs.get('instance')
    #     if instance and instance.imagen:
    #         self.fields['imagen'].widget = forms.ClearableFileInput()

    class Meta:
        model = Articulo
        fields = ['titulo', 'bajada', 'contenido', 'categoria', 'imagen', 'etiqueta']
        widgets = {
            # 'imagen': forms.ClearableFileInput(),
            'etiqueta': forms.CheckboxSelectMultiple(),
        }

class CategoriaForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre', 'activo', 'descripcion']

class EtiquetaForm(forms.ModelForm):
    class Meta:
        model = Etiqueta
        fields = ['nombre', 'activo']

class UsuariosForm(UserCreationForm):
    
    def __init__(self, *args, **kwargs):            # Estas lineas de código borran las helps que
        super().__init__(*args, **kwargs)           # dejan feo el formulario
        self.fields['username'].help_text = None 
        self.fields['password1'].help_text = None
        self.fields['password2'].help_text = None
    class Meta:
        model = Usuarios
        fields = ['username','email','first_name', 'last_name']

class LoginForm(AuthenticationForm):
    # Este formulario hereda de AuthenticationForm, por lo que no es necesario agregar campos adicionales.
    # Es solo para importar el formulario y usarlo en las views
    pass


class PermisosUsuarioForm(forms.ModelForm):
    class Meta:
        model = Usuarios
        fields = ['es_publico', 'es_colaborador', 'is_staff']

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ['contenido']

class CategoriaArticuloForm(forms.ModelForm):
    class Meta:
        model = Categoria_Articulo
        fields = ['id_articulo', 'id_categoria']


class ModificarUsuarioForm(forms.ModelForm):
    def clean_imagen(self):
        avatar = self.cleaned_data['avatar']

        if avatar:
            img = Image.open(avatar)
            if img.width > 1020 or img.height > 768:
                raise ValidationError("La imagen no puede ser mayor de 1020x768 píxeles.")

        return avatar

    class Meta:
        model = Usuarios
        fields = ['first_name', 'last_name', 'avatar']

    def __init__(self, *args, **kwargs):
        super(ModificarUsuarioForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].required = False


#############


class CategoriaCrearEditarForm(forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ['nombre', 'activo', 'descripcion']
        widgets = {
            'nombre': forms.TextInput(attrs={'required': 'required'}),
            'activo': forms.CheckboxInput(),
            'descripcion': forms.Textarea(attrs={'rows': 3, 'cols':25}),
        }


###################### formulario contacto


class FormContacto(forms.ModelForm):
    class Meta:
        model = MensajeContacto
        fields = ['nombre', 'email', 'mensaje']

        widgets = {
                'nombre': forms.TextInput(attrs={'class': 'form-control bg-light border-0', 'placeholder': 'Nombre', 'style': 'height: 55px;'}),
                'email': forms.EmailInput(attrs={'class': 'form-control bg-light border-0', 'placeholder': 'Email', 'style': 'height: 55px;'}),
                'mensaje': forms.Textarea(attrs={'class': 'form-control bg-light border-0', 'rows': 3, 'placeholder': 'Mensaje'}),
            }

INFO/blog/views.py
from typing import Any
from django.db import models
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from . import models
from django.urls import reverse
from django.views import generic
from .forms import UsuariosForm, LoginForm, ArticuloForm, ComentarioForm, ModificarUsuarioForm, CategoriaCrearEditarForm, EtiquetaForm, FormContacto
from django.contrib.auth import login, logout, authenticate
from .models import Articulo, Comentario, Usuarios, Categoria, Etiqueta, Categoria_Articulo
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import user_passes_test
# from django.contrib.auth.models import User
from .forms import PermisosUsuarioForm
from django.core.paginator import Paginator
from django.db.models import Q

def index_view(request):
    
    if request.method == 'POST':
        form = FormContacto(request.POST)
        if form.is_valid():
            form.save()  # Guarda el mensaje en la base de datos si el formulario es válido
            # Aquí puedes agregar lógica adicional si es necesario, como enviar un correo electrónico, etc.
    else:
        form = FormContacto()
    
    context = {
        'is_index': True,          # La variable is_index es para un if en el html que cambia el header 
        'form': form
    }
    return render(request, 'index.html', context)

def blog(request):
    nombre = request.GET.get('categoria', None)
    tags_nombre = request.GET.get('tags', None)
    print(tags_nombre)

    if nombre is not None:
        posts = Articulo.objects.filter(categoria__nombre=nombre).order_by('-creacion')[:6]

        categorias = Categoria.objects.all()
        # Obtengo los últimos 6 artículos ordenados por fecha de creación
        ultimos_post = Articulo.objects.filter(publicado=True).order_by('-creacion')[:6]

        # Obtengo todas las etiquetas
        etiquetas = Etiqueta.objects.all()

        # renderizo 4 post por página
        paginator = Paginator(posts, 4)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'posts': posts,
            'categorias': categorias,
            'ultimos_post': ultimos_post,
            'etiquetas': etiquetas,
            'page_obj': page_obj,
        }
        return render(request, "blog/blog.html", context)
    
    elif tags_nombre is not None:
        print('entro acá')

        posts = Articulo.objects.filter(etiqueta__nombre=tags_nombre).order_by('-creacion')[:6]
        categorias = Categoria.objects.all()
        # Obtengo los últimos 6 artículos ordenados por fecha de creación
        ultimos_post = Articulo.objects.filter(publicado=True).order_by('-creacion')[:6]

        etiquetas = Etiqueta.objects.all()

        # renderizo 4 post por página
        paginator = Paginator(posts, 4)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'posts': posts,
            'categorias': categorias,
            'ultimos_post': ultimos_post,
            'etiquetas': etiquetas,
            'page_obj': page_obj,
        }
        return render(request, "blog/blog.html", context)

    else:

        # Obtengo todos los posts
        posts = Articulo.objects.all()
        # Obtengo todas las categorías
        categorias = Categoria.objects.all()
        # Obtengo los últimos 6 artículos ordenados por fecha de creación
        ultimos_post = Articulo.objects.filter(publicado=True).order_by('-creacion')[:6]
        # Obtengo todas las etiquetas
        etiquetas = Etiqueta.objects.all()
        # renderizo 4 post por página
        paginator = Paginator(posts, 4)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
            'posts': posts,
            'categorias': categorias,
            'ultimos_post': ultimos_post,
            'etiquetas': etiquetas,
            'page_obj': page_obj,
        }
        return render(request, "blog/blog.html", context)


def post(request, post_id):
    post = get_object_or_404(Articulo, pk=post_id)

    # Obtengo todas las categorías
    categorias = Categoria.objects.all()

    # Obtengo los últimos 6 artículos ordenados por fecha de creación
    ultimos_post = Articulo.objects.filter(publicado=True).exclude(id=post_id).order_by('-creacion')[:6]

    
    if request.method == 'POST':
        comentario_texto = request.POST.get('comentario', '')
        if comentario_texto.strip():  # Asegurarse de que el comentario no esté en blanco
            comentario = Comentario(
                id_articulo=post,
                id_usuario=request.user,
                contenido=comentario_texto,
                
            )
            comentario.save()
    
    comentarios = Comentario.objects.filter(id_articulo=post_id)
    etiquetas = Etiqueta.objects.filter(articulo__id=post_id)
    print(f"{etiquetas}")

    context = {
        'post': post,
        'categorias': categorias,
        'ultimos_post': ultimos_post,
        'comentarios': comentarios,
        'etiquetas': etiquetas,
    }
    
    return render(request, 'post.html', context )


def register_view(request):

    if not request.user.is_anonymous:   # Si el usuario ya está logueado vuelve al index sin entrar a la vista
        return redirect('blog:index')
    
    if request.method == 'POST':
        form = UsuariosForm(request.POST)     # Procesa el formulario si se envió una solicitud POST
        
        if form.is_valid():

            user = form.save()                 # Almacena el usuario en la db

            if user is not None:
                login(request, user)           # Se loguea el usuario recién creado
                return redirect("blog:index")  # Se redirecciona al index
        
    else:
        form = UsuariosForm()
        print(form.errors)            # Si el formulario no es válido, se mostrará con los mensajes de error
    return render(request, 'register.html', {'form': form})

def login_view(request):                      # view que gestiona el login
    
    if not request.user.is_anonymous:   # Si el usuario ya está logueado vuelve al index sin entrar a la vista
        return redirect('blog:index')


    if request.method == 'POST':
        form = LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                # Si el login fue exitoso, redirige al usuario al index.
                return redirect('blog:index')
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})

def logout_view(request):
    logout(request)
    return redirect('blog:index')


def new_post_view(request):
    if request.user.is_anonymous:
        return redirect('blog:index')

    if request.method == 'POST':
        form = ArticuloForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.autor = request.user
            form.save()
            print('ingresó acá')
            
            return redirect('blog:post', post_id=article.id)
    else:
        form = ArticuloForm()

    return render(request, 'new_post.html', {'form': form})


def delete_comment(request, comentario_id):
    if request.method == "POST":
        comentario = get_object_or_404(Comentario, pk=comentario_id)
        if comentario.id_usuario == request.user or request.user.is_staff:
            comentario.delete()
    return redirect('blog:post', post_id=comentario.id_articulo.id)


# ----------------------------------- Edición de Permisos -----------------------

def is_admin(user):
    return user.is_staff


@user_passes_test(is_admin, login_url='/')
def edit_users_permissions(request):
    if request.method == 'POST':
        for user in Usuarios.objects.all():
            is_staff = request.POST.get('is_staff_{}'.format(user.id)) == 'on'
            es_colaborador = request.POST.get('es_colaborador_{}'.format(user.id)) == 'on'
            user.is_staff = is_staff
            user.es_colaborador = es_colaborador
            user.save()

    users = Usuarios.objects.all()
    form = PermisosUsuarioForm()

    return render(request, 'permissions.html', {'users': users, 'form': form})

# ------------------------------------ Edición de posts


def editar_post(request, post_id):
    post = get_object_or_404(Articulo, pk=post_id)

    if post.autor_id == request.user.id or is_admin(request.user):          # linea para asegurarse que solo el autor o admin puede editar

        if request.method == 'POST':
            form = ArticuloForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                form.save()
                return redirect('blog:post', post_id=post.id)
        else:
            form = ArticuloForm(instance=post)

        return render(request, 'editar_post.html', {'form': form})
    else:
        return redirect('blog:blog')



def eliminar_post(request, post_id, confirmacion=False):
    post = get_object_or_404(Articulo, pk=post_id)


    if post.autor_id == request.user.id or is_admin(request.user):           # linea para asegurarse que solo el autor o admin puede editar

        if request.method == 'POST':
        # if confirmacion:
            post.delete()
            return redirect('blog:blog')

        return render(request, 'eliminar_post.html', {'post': post})
    else:
        return redirect('blog:blog')


def modify_user(request):
    if request.user.is_anonymous:
        return redirect('blog:index')
    if request.method == 'POST':
        form = ModificarUsuarioForm(request.POST, request.FILES, instance=request.user)

INFO/blog/templates/blog/blog.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <!-- Blog Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        
        <div class="container py-5">
        <div class="row g-5">
            
            <!-- Blog list Start -->
            <div class="col-lg-8">
                
                <div class="row g-5">
                    {% if page_obj %}
                    {% for post in page_obj %}
                    <div class="col-md-6 wow slideInUp" data-wow-delay="0.1s">
                        <div class="blog-item bg-light rounded overflow-hidden">
                            <div class="blog-img position-relative overflow-hidden">
                                {% if post.imagen %}
                                <img class="img-fluid" src="{{ post.imagen.url }}" alt="{{ post.titulo }}">
                                {% else %}
                                <!-- Si no hay imagen, se puede mostrar una imagen predeterminada o dejar este espacio en blanco -->
                                <img class="img-fluid" src="{% static 'blog/img/blog-3.jpg' %}" alt="No Image">
                                {% endif %}
                                <a class="position-absolute top-0 start-0 bg-primary text-white rounded-end mt-5 py-2 px-4" href="{% url 'blog:post' post.id %}">{{post.categoria}}</a>
                            </div>
                            <div class="p-4">
                                <div class="d-flex mb-3">
                                    <small class="me-3"><i class="far fa-user text-primary me-2"></i>{{ post.autor }}</small>
                                    <small><i class="far fa-calendar-alt text-primary me-2"></i>{{ post.creacion|date:"F d, Y" }}</small>
                                </div>
                                
                                <h4 class="mb-3">{{ post.titulo }}</h4>
                                <p>{{ post.bajada }}</p>
                                <a class="text-uppercase" href="{% url 'blog:post' post.id %}">Leer más <i class="bi bi-arrow-right"></i></a>
                                
                                </div>
                               
                                {% if request.user == post.autor or request.user.is_superuser %}
                    <div class="btn-group" role="group">
                    <a href="{% url 'blog:editar_post' post.id %}" class="btn btn-sm btn-primary">Editar Post</a>
                    <a href="{% url 'blog:eliminar_post' post.id %}?confirmacion=True" class="btn btn-sm btn-danger">Eliminar Post</a>
            </div>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    {% else %}
        <p>No se encontraron resultados.</p>                       
    {% endif %}
    
    
    <div class="col-12 wow slideInUp d-flex justify-content-center" data-wow-delay="0.1s">
        <nav aria-label="Page navigation">
            <ul class="pagination pagination-lg m-0">
              {% if page_obj.has_previous %}
                  <li>
                      <a class="page-link rounded-0" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                          <span aria-hidden="true"><i class="bi bi-arrow-left"></i></span>
                      </a>
                  </li>
              {% endif %}
              {% if page_obj.paginator.num_pages != 1 %}
              {% for num in page_obj.paginator.page_range %}
                  {% if page_obj.number == num %}
                      <li class="page-item active"><a class="page-link" href="#">{{ num }}</a></li>
                  {% else %}
                      <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                  {% endif %}
              {% endfor %}
              {% endif %}
              {% if page_obj.has_next %}
                  <li>
                      <a class="page-link rounded-0" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                          <span aria-hidden="true"><i class="bi bi-arrow-right"></i></span>
                      </a>
                  </li>
              {% endif %}
            </ul>
          </nav>
    </div>
    </div>
    </div>
    <!-- Blog list End -->

                <!-- Sidebar Start -->
                <div class="col-lg-4">
                    <!-- Search Form Start -->
                    <div class="mb-5 wow slideInUp" data-wow-delay="0.1s">
                        <form method="get" action="{% url 'blog:buscar_articulos' %}">
                        <div class="input-group">
                            
                            <input type="text" name="q" class="form-control p-3" placeholder="Buscar publicación">
                            <button class="btn btn-primary px-4"><i class="bi bi-search"></i></button>
                            
                        </div>
                        </form>
                        
                    </div>
                    <!-- Search Form End -->
                    
                    <!-- boton nuevo post inicio -->
                    {% if request.user.es_colaborador or request.user.is_staff %}
                    <div class="d-flex justify-content-center mb-3">
                        <a class="btn btn-primary btn-lg m-2" href="{% url 'blog:new_post' %}" role="button">Nuevo Post</a>
                    </div>
                        {% if request.user.is_staff %}
                        <div class="d-flex justify-content-center mb-3">
                            <a class="btn btn-success btn-sm m-2" href="{% url 'blog:crear_editar_categorias' %}" role="button">Editar Categorías</a>
                        </div>
                        <div class="d-flex justify-content-center mb-3">
                            <a class="btn btn-success btn-sm m-2" href="{% url 'blog:crear_editar_etiqueta' %}" role="button">Editar Etiquetas</a>
                        </div>
                        {% endif %}
                    {% endif %}
                    <!-- boton nuevo post fin -->
                    
                    <!-- Category Start -->
                    <div class="mb-5 wow slideInUp" data-wow-delay="0.1s">
                        <div class="section-title section-title-sm position-relative pb-3 mb-4">
                            <h3 class="mb-0">Categorias</h3>
                        </div>
                        <div class="link-animated d-flex flex-column justify-content-start">
                            {% for categoria in categorias %}
                            <a class="h5 fw-semi-bold bg-light rounded py-2 px-3 mb-2" href="{% url 'blog:blog' %}?categoria={{ categoria.nombre }}"><i class="bi bi-arrow-right me-2"></i> {{categoria.nombre}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Category End -->
                    
                    <!-- Recent Post Start -->
                    <div class="mb-5 wow slideInUp" data-wow-delay="0.1s">
                        <div class="section-title section-title-sm position-relative pb-3 mb-4">
                            <h3 class="mb-0">Post Recientes</h3>
                        </div>
                        {% for post in ultimos_post %}
                        <div class="d-flex rounded overflow-hidden mb-3">
                            <img class="img-fluid" src="{{ post.imagen.url }}" style="width: 100px; height: 100px; object-fit: cover;" alt="">
                            <a href="{% url 'blog:post' post.id %}" class="h5 fw-semi-bold d-flex align-items-center bg-light px-3 mb-0">{{ post.titulo }}</a>
                        </div>
                        {% endfor %}
                        
                    </div>
                    <!-- Recent Post End -->
                        
                        <!-- Tags Start -->
                        <div class="mb-5 wow slideInUp" data-wow-delay="0.1s">
                            <div class="section-title section-title-sm position-relative pb-3 mb-4">
                                <h3 class="mb-0">Tag Cloud</h3>
                            </div>
                            <div class="d-flex flex-wrap m-n1">
                                {% for etiqueta in etiquetas  %}
                                    <a href="{% url 'blog:blog' %}?tags={{ etiqueta.nombre }}" class="btn btn-light m-1">{{etiqueta.nombre}}</a>
                                {% endfor %}
                                
                            </div>
                        </div>
                        <!-- Tags End -->
                    </div>
                <!-- Sidebar End -->
            </div>
        </div>
    </div>
    <!-- Blog End -->
    {% endblock %}
    

INFO/blog/templates/blog/crear_editar_categorias.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<div class="container d-flex justify-content-center align-items center" >
    <div class="card" style="width: 18rem; margin: 1em">
    <h1>Crear o Editar Categoría</h1>
    
    <div class="card-body">
        
    <form method="post">
        {% csrf_token %}
        {% if categorias %}
            <label for="categoria_seleccionada">Seleccione una categoría o creela:</label>
            <br>
            <select id="categoria_seleccionada" name="categoria_seleccionada">
                <option value="" selected>Seleccione una categoría</option>
                {% for categoria in categorias %}
                    <option value="{{ categoria.id }}">{{ categoria.nombre }}</option>
                {% endfor %}
            </select>
            
            <br>
        {% endif %}
        {{ form.as_p }}
        <input type="submit" value="Crear/Guardar">
        <button type="submit" name="eliminar_categoria">Eliminar</button>
    </form>

    {% if form.errors %}
        <div style="color: red;">
            {{ form.errors }}
        </div>
    {% endif %}
</div>
</div>

</div>

    <script>
        document.getElementById('categoria_seleccionada').addEventListener('change', function() {
            var categoriaId = this.value;
            if (categoriaId) {
                fetch('/categoria/' + categoriaId + '/json/')
                .then(response => response.json())
                .then(data => {
                    document.getElementById('id_nombre').value = data.nombre;
                    document.getElementById('id_activo').checked = data.activo;
                    document.getElementById('id_descripcion').value = data.descripcion;
                });
            }
        });
    </script>
    {% endblock %}

INFO/blog/templates/blog/header_blog.html
<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner"></div>
</div>
<!-- Spinner End -->




<!-- Navbar Start -->
<div class="container-fluid position-relative p-0">
    <nav class="navbar navbar-expand-lg navbar-dark px-5 py-3 py-lg-0">
        <a href="{% url 'blog:index' %}" class="navbar-brand p-0">
            <h1 class="m-0"><i class="fa fa-user-tie me-2"></i>TecnoPower</h1>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="fa fa-bars"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav ms-auto py-0">
                <a href="{% url 'blog:index' %}" class="nav-item nav-link">Home</a>
                {% comment %} <a href="about.html" class="nav-item nav-link">Acerca de</a> {% endcomment %}
                <a href="{% url 'blog:blog' %}" class="nav-item nav-link active">Blog</a>
                {% comment %} <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle active" data-bs-toggle="dropdown">Blog</a>
                    <div class="dropdown-menu m-0">
                        <a href="blog.html" class="dropdown-item active">Blog Grid</a>
                        <a href="detail.html" class="dropdown-item">Blog Detail</a>
                    </div>
                </div> {% endcomment %}
                <div class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Más</a>
                    <div class="dropdown-menu m-0">
                        {% if user.is_authenticated %}
                        <a href="{% url 'blog:modify_user' %}" class="dropdown-item">Perfil</a>
                        {% endif %}

                        <a href="{% url 'blog:index' %}?#experience" class="dropdown-item">Nuestra experiencia</a>
                        <a href="{% url 'blog:index' %}?#team" class="dropdown-item">Equipo</a>
                        <a href="{% url 'blog:index' %}?#testimonial" class="dropdown-item">Testimonios</a>
                        <a href="{% url 'blog:index' %}?#acerca" class="dropdown-item">Acerca de</a>
                        <a href="{% url 'blog:index' %}?#contacto" class="dropdown-item">Contacto</a>
                        {% if request.user.is_staff %}
                        <a href="{% url 'blog:edit_users_permissions' %}" class="dropdown-item">Editar permisos</a>
                        {% endif %}
                    </div>
                </div>
                {% comment %} <a href="contact.html" class="nav-item nav-link">Contacto</a> {% endcomment %}
                {% if user.is_authenticated %}
                <a href="{% url 'blog:logout' %}" class="nav-item nav-link">Salir</a>
                {% endif %}
            </div>
            <butaton type="button" class="btn text-primary ms-3" data-bs-toggle="modal" data-bs-target="#searchModal"><i class="fa fa-search"></i></butaton>
        </div>
    </nav>

    <div class="container-fluid bg-primary py-5 bg-header" style="margin-bottom: 0px;">
        <div class="row py-5">
            <div class="col-12 pt-lg-5 mt-lg-5 text-center">
                <h1 class="display-4 text-white animated zoomIn">Tu Blog Sobre IA</h1>
                {% comment %} <a href="" class="h5 text-white">By</a> {% endcomment %}
                
                <a href="" class="h5 text-white">By TecnoPower</a>
            </div>
        </div>
    </div>
</div>
<!-- Navbar End -->

<!-- Full Screen Search Start -->
<div class="modal fade" id="searchModal" tabindex="-1">
    <div class="modal-dialog modal-fullscreen">
        <div class="modal-content" style="background: rgba(9, 30, 62, .7);">
            <div class="modal-header border-0">
                <button type="button" class="btn bg-white btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex align-items-center justify-content-center">
                
                <form method="get" action="{% url 'blog:buscar_articulos' %}" class="modal-body d-flex align-items-center justify-content-center">
                <div class="input-group" style="max-width: 600px;">
                    <input type="text" name="q" class="form-control bg-transparent border-primary p-3" placeholder="Ingrese aquí su búsqueda">
                    <button class="btn btn-primary px-4"><i class="bi bi-search"></i></button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- Full Screen Search End -->